### ISSUE TITLE
escaped quote \" doesn't work

### ISSUE THREAD

**Issue by mariusa** [JairusSW/as-json#31]
Hi,

```
import { JSON } from "json-as/assembly"

@json
class Vec2 {
    x: f32
    y: f32
}

@json
class Player {
    firstName: string
    lastName: string
    lastActive: i32[]
    age: i32
    pos: Vec2
    isVerified: boolean
}

const data: Player = {
    firstName: "Emmet",
    lastName: "West",
    lastActive: [8, 27, 2022],
    age: 23,
    pos: {
        x: -3.4,
        y: 1.2
    },
    isVerified: true
}

let stringified2 = `{"firstName":"\"John\"","lastName":"West","age":23}`

const parsed = JSON.parse<Player>(stringified2)
console.log('parsed')
console.log(parsed.firstName)

```

gives
```
abort: Cannot find key:  in assembly/testjs.ts(28:9)
```

This
```
let stringified2 = `{"firstName":"\"John\":\"Smith\"","lastName":"West","age":23}`
```
gives something different:
```
abort: Cannot find key: : in assembly/testjs.ts(28:9)
```

Thanks!

**Comment by JairusSW** [comment]
Thank you. I'll work on this

**Comment by JairusSW** [comment]
Here's what's going on.
As-json can't really parse malformed JSON, it just throws an error. However, I am working on a json verifier as a side project.
This is how JSON handles quotes inside of a string. Since JSON uses `"` by default, it must escape it. So, `"foo":"ba"r"` serializes into `"foo": "ba\"r"`. In AssemblyScript (and all strings in general), you are using the escape code which allows you to have double quotes in a string with double quotes. But if you want the actual `\` slash character, you need to escape the slash.

Here's what you need to do:

`{"firstName":"\"John\"","lastName":"West","age":23}` is malformed JSON. You need to double-slash your backslashes.
So, do this instead
`{"firstName":"\\"John\\"","lastName":"West","age":23}` which is valid JSON and should be parsed correctly

Hope this helps :)

**Comment by mariusa** [comment]
Hi & thanks for your explanation!

I don't want the `\`. But double quoting solves that particular example, the end results has `"`.

Use case: I need to parse a JSON with another stringified JSON in one of the fields, then parse that afterwards. 

```js
// in js
let player = { "firstName": "John", "lastName": "West", "age": 23 }
let contacts = { player: JSON.stringify(player), type: 'friends' }
console.log(JSON.stringify(contacts))
```
outputs
```
{"player":"{\"firstName\":\"John\",\"lastName\":\"West\",\"age\":23}","type":"friends"}
```

Then I need to parse this, 2 times:

```js
// in as
import { JSON } from "json-as/assembly"

@json
class Vec2 {
    x: f32
    y: f32
}

@json
class Player {
    firstName: string
    lastName: string
    lastActive: i32[]
    age: i32
    pos: Vec2
    isVerified: boolean
}

@json
class Contacts {
    type: string
    player: string
}
/*
const data: Player = {
    firstName: "Emmet",
    lastName: "West",
    lastActive: [8, 27, 2022],
    age: 23,
    pos: {
        x: -3.4,
        y: 1.2
    },
    isVerified: true
}*/


let stringifiedc = `{"player":"{\"firstName\":\"John\",\"lastName\":\"West\",\"age\":23}","type":"friends"}` // original
// stringifiedc = stringifiedc.replaceAll('\\"', '\\\\\\"')  // escape? Still doesn't work
console.log('input')
console.log(stringifiedc)
// const parsed = JSON.parse<Player>(stringified2)
const contacts = JSON.parse<Contacts>(stringifiedc)
console.log('parsed Contacts')
console.log(`${contacts.type}; ${contacts.player}`)
// if this would have worked:
console.log('parsed player:Player')
const parsedP = JSON.parse<Player>(contacts.player)
```

gives

```
input
{"player":"{"firstName":"John","lastName":"West","age":23}","type":"friends"}
abort: Cannot find key: : in assembly/testjs.ts(12:9)
```

**Comment by mariusa** [comment]
This might be a good test for your library :)

**Comment by JairusSW** [comment]
I finally understand what you are asking.
Fix should be straightforward. I'll work on this when I have time. Just fixed issue #34 so I'm taking a break for the rest of the day

**Comment by JairusSW** [comment]
I'm so sorry, my mom had me grounded until today
I'll release within the next day or so

**Comment by JairusSW** [comment]
This works perfectly in the latest version
```js
import {
  JSON
} from "json-as/assembly";
@json
class Player {
  firstName: string
  lastName: string
  age: i32
}

@json
class Contacts {
  type: string
  player: string
}

const player: Player = {
  firstName: "John",
  lastName: "West",
  age: 23
}

const contact: Contacts = {
  player: JSON.stringify(player),
  type: "friends"
}

const stringifiedContact = JSON.stringify(contact);
console.log("Input (Should see backslashes logged): " + stringifiedContact);
const contacts = JSON.parse<Contacts>(stringifiedContact)
console.log("Player: " + contacts.player);
console.log("Type: " + contacts.type);
const parsedPlayer = JSON.parse<Player>(contacts.player);
console.log("Final Player: " + JSON.stringify(parsedPlayer));
console.log("Final Result (Contacts): " + JSON.stringify(contacts));
```
Here is the output in the console

```bash
Input (Should see backslashes logged): {"type":"friends","player":"{\"firstName\":\"John\",\"lastName\":\"West\",\"age\":23}"}
Player: {"firstName":"John","lastName":"West","age":23}
Type: friends
Final Player: {"firstName":"John","lastName":"West","age":23}
Final Result (Contacts): {"type":"friends","player":"{\"firstName\":\"John\",\"lastName\":\"West\",\"age\":23}"}
```
If I understand this correctly, it seems that you were parsing the string 
```js
const stringifiedc = '{"player":"{\"firstName\":\"John\",\"lastName\":\"West\",\"age\":23}","type":"friends"}'
```
However, the escapes only escaped the quote, but not the backslash resulting in this being received by as-json for parsing
```js
Parsing Recieved Data: {"player":"{"firstName":"John","lastName":"West","age":23}","type":"friends"}
```
Which ended up, due to the object parsing algorithm, recognizing `"{"`, `","`, `":"`, `","`, and `":"` being recognized as the opening and closing quotes of a string, which messed with a lot of things.
Since the type of `Contact.player` is `string`, it starts with a quote and we know that JSON cannot have a quote within a JSON string unless it is escaped resulting in malformed JSON like before

PTAL at my previous comment and that should contain the fix

**Comment by mariusa** [comment]
You're right, it does work! I was confused by copy-pasting the string in source code. Thanks so much, Jairus!
